# SPDX-FileCopyrightText: 2020 Tilman Vatteroth
#
# SPDX-License-Identifier: MIT

name: REUSE Compliance Check

on: [push, pull_request]

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v2
